sudo: require
services:
    - docker
before_install :
    - docker build -t woeden/react-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true woeden/react-test npm test

after_success:
    - docker build -t woeden/multi-client ./client
    - docker build -t woeden/multi-nginx ./nginx
    - docker build -t woeden/multi-server ./server
    - docker build -t woeden/multi-worker ./worker
    # LOGIN TO DOCKER CLI
    - docker login 