sudo: require
services:
    - docker
before_install :
    - docker build ./client -t deniswoeffray/react-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true deniswoeffray/react-test npm test -- --coverage

after_success:
    - docker build -t deniswoeffray/multi-client ./client
    - docker build -t deniswoeffray/multi-nginx ./nginx
    - docker build -t deniswoeffray/multi-server ./server
    - docker build -t deniswoeffray/multi-worker ./worker
    # LOGIN TO DOCKER CLI
    - docker login -u $DOCKER_USER -p $DOCKER_PWD
    # Push to Docker Hub
    - docker push deniswoeffray/multi-client
    - docker push deniswoeffray/multi-nginx
    - docker push deniswoeffray/multi-server
    - docker push deniswoeffray/multi-worker